baseURL = 'https://sudodo.github.io/shin-academia-web/'
defaultContentLanguage = 'ja'
title = 'Shin-academia (シン・アカデミア）'
theme = 'PaperMod'

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
    languageAltTitle = 'En'
    weight = 2
    title = 'Shin-academia'

    [languages.en.params.label]
      text = "Shin-academia"
    [languages.en.params.footer]
      text = "We do not publish on social media."
  [languages.ja]
    languageName = '日本語'
    languageCode = 'ja'
    languageAltTitle = 'Ja'
    weight = 1
    title = 'シン・アカデミア'

    [languages.ja.params.label]
      text = "シン・アカデミア"
    [languages.ja.params.homeInfoParams]
      Title = "シン・アカデミアへようこそ"
      Content = "アカデミアとテクノロジーの革新。最新ニュース、研究、サービスをご覧ください。"

[languages.ja.menu]
  [[languages.ja.menu.main]]
    identifier = "home-ja"
    name = "ホーム"
    url = "/ja/"
    weight = 1
  [[languages.ja.menu.main]]
    identifier = "about-ja"
    name = "概要"
    url = "/ja/about/"
    weight = 2
  [[languages.ja.menu.main]]
    identifier = "services-ja"
    name = "サービス"
    url = "/ja/services/"
    weight = 5
  [[languages.ja.menu.main]]
    identifier = "lab-ja"
    name = "ラボ"
    url = "/ja/lab/"
    weight = 4
  [[languages.ja.menu.main]]
    identifier = "members-ja"
    name = "メンバー"
    url = "/ja/members/"
    weight = 3
  [[languages.ja.menu.main]]
    identifier = "blog-ja"
    name = "ブログ"
    url = "/ja/posts/"
    weight = 5.5
  [[languages.ja.menu.main]]
    identifier = "contact-ja"
    name = "お問い合わせ"
    url = "/ja/contact/"
    weight = 6

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home-en"
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[languages.en.menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 3
  [[languages.en.menu.main]]
    identifier = "lab"
    name = "Lab"
    url = "/lab/"
    weight = 4
  [[languages.en.menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members/"
    weight = 5
  [[languages.en.menu.main]]
    identifier = "blog-en"
    name = "Blog"
    url = "/posts/"
    weight = 5.5
  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

[params]
  defaultContentLanguageInSubdir = true
  env = "production"
  robotsNoIndex = true

  [params.footer]
    text = "ソーシャルメディアでの発信は現在行なっておりません"
  # mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowLanguageSwitcher = true
  defaultTheme = "auto"
  math = true
  displayFullLangName = false

  [params.homeInfoParams]
    Title = "シン・アカデミアへようこそ"
    Content = "アカデミアとテクノロジーの革新。最新ニュース、研究、サービスをご覧ください。"

[languages.en.params.homeInfoParams]
  Title = "Welcome to Shin-academia"
  Content = "Innovating Academia and Technology. Explore our latest news, research, and services."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

relativeURLs = false
canonifyURLs = true
