baseURL = 'https://sudodo.github.io/shin-academia-web/'
defaultContentLanguage = 'ja'
title = 'Shin-academia (シン・アカデミア）'
theme = 'PaperMod'

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
    languageAltTitle = 'En'
    weight = 2
    title = 'Shin-academia'

    [languages.en.params.footer]
      text = "We do not publish on social media."
  [languages.ja]
    languageName = '日本語'
    languageCode = 'ja'
    languageAltTitle = 'Ja'
    weight = 1
    title = 'シン・アカデミア'

    [languages.ja.params.homeInfoParams]
      Title = "シン・アカデミアへようこそ"
      Content = "アカデミアとテクノロジーの革新。最新ニュース、研究、サービスをご覧ください。"

[languages.ja.menu]
  [[languages.ja.menu.main]]
    identifier = "home-ja"
    name = "ホーム"
    url = "/ja/"
    weight = 1
  [[languages.ja.menu.main]]
    identifier = "about-ja"
    name = "概要"
    url = "/ja/about/"
    weight = 2
  [[languages.ja.menu.main]]
    identifier = "services-ja"
    name = "サービス"
    url = "/ja/services/"
    weight = 3
  [[languages.ja.menu.main]]
    identifier = "lab-ja"
    name = "ラボ"
    url = "/ja/lab/"
    weight = 4
  [[languages.ja.menu.main]]
    identifier = "contact-ja"
    name = "お問い合わせ"
    url = "/ja/contact/"
    weight = 5

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home-en"
    name = "Home"
    url = "/en/"
    weight = 1
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/en/about/"
    weight = 2
  [[languages.en.menu.main]]
    identifier = "services"
    name = "Services"
    url = "/en/services/"
    weight = 3
  [[languages.en.menu.main]]
    identifier = "lab"
    name = "Lab"
    url = "/en/lab/"
    weight = 4
  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/en/contact/"
    weight = 5

[params]
  defaultContentLanguageInSubdir = true
  env = "production"
  robotsNoIndex = true

  [params.footer]
    text = "当サイトはソーシャルメディアでの発信を行っておりません。"
  # mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowLanguageSwitcher = true
  defaultTheme = "auto"
  math = true
  displayFullLangName = false

  [params.homeInfoParams]
    Title = "シン・アカデミアへようこそ"
    Content = "アカデミアとテクノロジーの革新。最新ニュース、研究、サービスをご覧ください。"

[languages.en.params.homeInfoParams]
  Title = "Welcome to Shin-academia"
  Content = "Innovating Academia and Technology. Explore our latest news, research, and services."
